version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  staging_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/staging/django/Dockerfile

    image: api_bddw_com_staging_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.staging/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/staging/postgres/Dockerfile
    image: api_bddw_com_staging_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data # we want to use the extant production db that's on the server for our staging site
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.staging/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/staging/traefik/Dockerfile
    image: api_bddw_com_staging_traefik
    depends_on:
      - django
    volumes:
      - staging_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    image: docker.io/redis:6

  awscli:
    build:
      context: .
      dockerfile: ./compose/staging/aws/Dockerfile
    env_file:
      - ./.envs/.staging/.django
    volumes:
      - staging_postgres_data_backups:/backups:z
