# Generated by Django 4.2.9 on 2024-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_menulist_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropDownMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
