# Generated by Django 4.2.9 on 2024-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_dropdownmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
