# Generated by Django 4.2.9 on 2024-02-13 13:14

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_productimage_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=api.models.CloudFrontImageField(upload_to=""),
        ),
    ]
