# Generated by Django 4.2.9 on 2024-02-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_historicalproductimage_historicalproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproductimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
