# Generated by Django 4.2.9 on 2024-02-13 19:27

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_historicalproduct_blurb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulistitem",
            name="image",
            field=api.models.CloudFrontImageField(upload_to=""),
        ),
    ]
