# Generated by Django 4.2.9 on 2024-02-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_menulistitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmenulist",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmenulistitem",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmenulistitem",
            name="menu_list",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproductimage",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproductimage",
            name="product",
        ),
        migrations.DeleteModel(
            name="HistoricalDropDownMenu",
        ),
        migrations.DeleteModel(
            name="HistoricalMenuList",
        ),
        migrations.DeleteModel(
            name="HistoricalMenuListItem",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="HistoricalProductImage",
        ),
    ]
