# Generated by Django 4.2.9 on 2024-02-14 20:41

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_historicalmenulist_history_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulist",
            name="name",
            field=models.CharField(help_text="this will appear at the top of the menu template", max_length=255),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="image",
            field=api.models.CloudFrontImageField(
                help_text="the 'thumbnail' image you want for this menu item", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="menu_list",
            field=models.ForeignKey(
                help_text="the menu list this menu item bleongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MenuListItems",
                to="api.menulist",
            ),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="name",
            field=models.CharField(help_text="the name of the menu item", max_length=255),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="order",
            field=models.IntegerField(help_text="the order you want this menu item to appear"),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="url",
            field=models.CharField(help_text="the path for lnking", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="blurb",
            field=models.TextField(
                blank=True, help_text="The blurb text that appears underneath the carousel", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="The name you want to appear in the template", max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="caption",
            field=models.CharField(blank=True, help_text="image caption", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=api.models.CloudFrontImageField(help_text="upload your image here", upload_to=""),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.IntegerField(help_text="the order the image should appear in the carousel"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="image for what product?",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.product",
            ),
        ),
    ]
