# Generated by Django 4.2.9 on 2024-02-14 20:45

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_menulist_name_alter_menulistitem_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulist",
            name="name",
            field=models.CharField(help_text="name appears at the top of the menu template", max_length=255),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="image",
            field=api.models.CloudFrontImageField(
                help_text="'thumbnail' image you want for this menu item", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="menu_list",
            field=models.ForeignKey(
                help_text="menu list this menu item bleongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MenuListItems",
                to="api.menulist",
            ),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="name",
            field=models.CharField(help_text="name of the menu item", max_length=255),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="order",
            field=models.IntegerField(help_text="order item to appear"),
        ),
        migrations.AlterField(
            model_name="menulistitem",
            name="url",
            field=models.CharField(
                help_text="path for linking: /list/list-name or /product/product-name", max_length=255
            ),
        ),
    ]
