# Generated by Django 4.2.9 on 2024-02-15 15:27

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_menulist_name_alter_menulistitem_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulistitem",
            name="image",
            field=api.models.CloudFrontImageField(
                help_text="'thumbnail' image you want for this menu item", upload_to=api.models.LowercaseRename("")
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=api.models.CloudFrontImageField(
                help_text="upload your image here", upload_to=api.models.LowercaseRename("")
            ),
        ),
    ]
