# Generated by Django 4.2.9 on 2024-02-15 15:34

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_menulistitem_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulistitem",
            name="image",
            field=api.models.CloudFrontImageField(
                help_text="'thumbnail' image you want for this menu item", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=api.models.CloudFrontImageField(help_text="upload your image here", upload_to=""),
        ),
    ]
