# Generated by Django 4.2.9 on 2024-02-19 18:48

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_menulistitem_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=api.models.CloudFrontImageField(
                blank=True,
                default=None,
                help_text="thumbnail of image",
                null=True,
                # upload_to=api.models.LowercaseThumbnailRename(""),
            ),
        ),
    ]
