# Generated by Django 4.2.9 on 2024-02-19 19:24

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_productimage_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="thumbnail",
            field=api.models.CloudFrontImageField(
                blank=True,
                default=None,
                help_text="thumbnail of image",
                null=True,
                upload_to=api.models.LowercaseRename(""),
            ),
        ),
    ]
