# Generated by Django 4.2.9 on 2024-02-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_landingpageimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulistitem",
            name="menu_list",
            field=models.ForeignKey(
                help_text="menu list where this item appears",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MenuListItems",
                to="api.menulist",
            ),
        ),
    ]
