# Generated by Django 4.2.9 on 2024-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_landingpageimage_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropdownmenu",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="menulist",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="menulistitem",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
