# Generated by Django 4.2.9 on 2024-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_dropdownmenu_updated_on_menulist_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulistitem",
            name="url",
            field=models.CharField(
                help_text="path for linking: /list/list-name or /product/product-name - outide links must start with http",
                max_length=255,
            ),
        ),
    ]
