# Generated by Django 4.2.9 on 2025-10-13 16:07

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_menulistitem_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LandingPageFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("horizontal_background", "Horizontal Background"),
                            ("vertical_background", "Vertical Background"),
                            ("horizontal_map", "Horizontal Map"),
                            ("vertical_map", "Vertical Map"),
                            ("logo", "Logo"),
                            ("catalog", "Catalog"),
                            ("auction", "Auction"),
                        ],
                        max_length=25,
                    ),
                ),
                ("image", api.models.CloudFrontImageField(upload_to=api.models.LowercaseRename("landing_pages/"))),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="api.landingpageversion"
                    ),
                ),
            ],
            options={
                "unique_together": {("version", "file_type")},
            },
        ),
    ]
